<?php

/**
 * BaseAlertaMedica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pais_id
 * @property clob $descripcion
 * @property enum $nivel_riesgo
 * @property PaisSalud $PaisSalud
 * 
 * @method integer      get()             Returns the current record's "pais_id" value
 * @method clob         get()             Returns the current record's "descripcion" value
 * @method enum         get()             Returns the current record's "nivel_riesgo" value
 * @method PaisSalud    get()             Returns the current record's "PaisSalud" value
 * @method AlertaMedica set()             Sets the current record's "pais_id" value
 * @method AlertaMedica set()             Sets the current record's "descripcion" value
 * @method AlertaMedica set()             Sets the current record's "nivel_riesgo" value
 * @method AlertaMedica set()             Sets the current record's "PaisSalud" value
 * 
 * @package    MiReto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlertaMedica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alerta_medica');
        $this->hasColumn('pais_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('nivel_riesgo', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Bajo',
              1 => 'Medio',
              2 => 'Alto',
             ),
             'default' => 'Bajo',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PaisSalud', array(
             'local' => 'pais_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}