<?php

/**
 * BasePaisSalud
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $continente_id
 * @property string $nombre
 * @property integer $casos_totales
 * @property integer $muertes
 * @property string $codigo_iso
 * @property Continente $Continente
 * @property Doctrine_Collection $AlertaMedica
 * 
 * @method integer             get()              Returns the current record's "continente_id" value
 * @method string              get()              Returns the current record's "nombre" value
 * @method integer             get()              Returns the current record's "casos_totales" value
 * @method integer             get()              Returns the current record's "muertes" value
 * @method string              get()              Returns the current record's "codigo_iso" value
 * @method Continente          get()              Returns the current record's "Continente" value
 * @method Doctrine_Collection get()              Returns the current record's "AlertaMedica" collection
 * @method PaisSalud           set()              Sets the current record's "continente_id" value
 * @method PaisSalud           set()              Sets the current record's "nombre" value
 * @method PaisSalud           set()              Sets the current record's "casos_totales" value
 * @method PaisSalud           set()              Sets the current record's "muertes" value
 * @method PaisSalud           set()              Sets the current record's "codigo_iso" value
 * @method PaisSalud           set()              Sets the current record's "Continente" value
 * @method PaisSalud           set()              Sets the current record's "AlertaMedica" collection
 * 
 * @package    MiReto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaisSalud extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais_salud');
        $this->hasColumn('continente_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('casos_totales', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('muertes', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('codigo_iso', 'string', 10, array(
             'type' => 'string',
             'unique' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Continente', array(
             'local' => 'continente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('AlertaMedica', array(
             'local' => 'id',
             'foreign' => 'pais_id'));
    }
}