<?php

/**
 * BaseContinente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property Doctrine_Collection $PaisSalud
 * 
 * @method string              get()          Returns the current record's "nombre" value
 * @method Doctrine_Collection get()          Returns the current record's "PaisSalud" collection
 * @method Continente          set()          Sets the current record's "nombre" value
 * @method Continente          set()          Sets the current record's "PaisSalud" collection
 * 
 * @package    MiReto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContinente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('continente');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PaisSalud', array(
             'local' => 'id',
             'foreign' => 'continente_id'));
    }
}