<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2026/03/03 15:42:23

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=MiReto',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
