<?php

/**
 * AlertaMedicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlertaMedicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlertaMedicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlertaMedica');
    }
}