<?php

/**
 * ContinenteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContinenteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContinenteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Continente');
    }
}