<?php

/**
 * PaisSaludTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PaisSaludTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PaisSaludTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PaisSalud');
    }
}