# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      # Cambiamos 'localhost' por 'db' que es el nombre de tu servicio en Docker
      dsn:      'mysql:host=db;dbname=symfony_db'
      username: symfony_user
      password: admin
      attributes:
        # Esto es vital para MySQL 8.4 y PHP 7/8
        quote_identifier: true
