<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2026/03/03 19:55:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=db;dbname=symfony_db',
  'username' => 'symfony_user',
  'password' => 'admin',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
