<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2026/03/03 19:55:13
return array(

  // sfTwigPlugin_module_libs

  // sfTwigPlugin_lib

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'swift_doctrinespool' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfwidgetformdoctrinechoice' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineexception' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinepager' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroutecollection' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineformfiltergenerator' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformgenerator' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfvalidatordoctrinechoice' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwebdebugpaneldoctrine' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinecli' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrinerecord' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinebuilddbtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebuildformstask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuildsqltask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedataloadtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedatadumptask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinemigratetask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuildmodeltask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegenerateadmintask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinedqltask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildschematask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrineinsertsqltask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedropdbtask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebasetask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrineconnectionlistener' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfformfilterdoctrine' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sftesterdoctrine' => '/workspaces/ProyectSymfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',

  // project
  'baseformfilterdoctrine' => '/workspaces/ProyectSymfony/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'paissaludformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/PaisSaludFormFilter.class.php',
  'continenteformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/ContinenteFormFilter.class.php',
  'alertamedicaformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/AlertaMedicaFormFilter.class.php',
  'basepaissaludformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/base/BasePaisSaludFormFilter.class.php',
  'basealertamedicaformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/base/BaseAlertaMedicaFormFilter.class.php',
  'basecontinenteformfilter' => '/workspaces/ProyectSymfony/lib/filter/doctrine/base/BaseContinenteFormFilter.class.php',
  'baseform' => '/workspaces/ProyectSymfony/lib/form/BaseForm.class.php',
  'continenteform' => '/workspaces/ProyectSymfony/lib/form/doctrine/ContinenteForm.class.php',
  'alertamedicaform' => '/workspaces/ProyectSymfony/lib/form/doctrine/AlertaMedicaForm.class.php',
  'baseformdoctrine' => '/workspaces/ProyectSymfony/lib/form/doctrine/BaseFormDoctrine.class.php',
  'paissaludform' => '/workspaces/ProyectSymfony/lib/form/doctrine/PaisSaludForm.class.php',
  'basealertamedicaform' => '/workspaces/ProyectSymfony/lib/form/doctrine/base/BaseAlertaMedicaForm.class.php',
  'basecontinenteform' => '/workspaces/ProyectSymfony/lib/form/doctrine/base/BaseContinenteForm.class.php',
  'basepaissaludform' => '/workspaces/ProyectSymfony/lib/form/doctrine/base/BasePaisSaludForm.class.php',

  // project_model
  'alertamedicatable' => '/workspaces/ProyectSymfony/lib/model/doctrine/AlertaMedicaTable.class.php',
  'continente' => '/workspaces/ProyectSymfony/lib/model/doctrine/Continente.class.php',
  'alertamedica' => '/workspaces/ProyectSymfony/lib/model/doctrine/AlertaMedica.class.php',
  'paissalud' => '/workspaces/ProyectSymfony/lib/model/doctrine/PaisSalud.class.php',
  'paissaludtable' => '/workspaces/ProyectSymfony/lib/model/doctrine/PaisSaludTable.class.php',
  'continentetable' => '/workspaces/ProyectSymfony/lib/model/doctrine/ContinenteTable.class.php',
  'basecontinente' => '/workspaces/ProyectSymfony/lib/model/doctrine/base/BaseContinente.class.php',
  'basepaissalud' => '/workspaces/ProyectSymfony/lib/model/doctrine/base/BasePaisSalud.class.php',
  'basealertamedica' => '/workspaces/ProyectSymfony/lib/model/doctrine/base/BaseAlertaMedica.class.php',

  // application
  'myuser' => '/workspaces/ProyectSymfony/apps/frontend/lib/myUser.class.php',

  // modules
);
